INCLUDE (ProjectMacros)
################################################################################
# Customize here : headers
# directory naming is free except: 
#  PROJECT_HEADER_MAIN: root directory for header files
################################################################################
# DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  # PROJECT_HEADER_MAIN
  # "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_CAMERA_SHAPE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/camerashapes/*.hpp")

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_COLOR_HANDLER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/colorhandlers/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_EXCEPTION
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/exceptions/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_IO
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/io/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_IO_IMAGE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/io/image/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_IO_MESH
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/io/mesh/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_IO_EXTERNAL
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/io/external/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_IO_SCENERYV2
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/io/sceneryV2/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_LIGHT_SOURCE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/lightsources/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_MATERIAL
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/materials/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_MATH
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/maths/*.hpp")
  
# DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  # PROJECT_HEADER_MPI
  # "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/mpi/*.hpp")     
      
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_OBJECT_SHAPE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/objectshapes/*.hpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_PHYSIC
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/physics/*.hpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_RAYTRACER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/raytracers/*.hpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_RENDERER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/renderers/*.hpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_STRUCTURE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/structures/*.hpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_ENVIRONMENT
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/environments/*.hpp")   

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_CORE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/core/*.hpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_CORE_TASKMANAGER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/core/taskmanager/*.hpp")

DECLARE_SRC_DIRECTORY (GLOBAL_HEADER_FILES 
  PROJECT_HEADER_CORE_TASKEXECUTOR
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${HEADER_DIRNAME}/core/taskexecutor/*.hpp")
  
################################################################################
# Customize here : sources
# directory naming is free except: 
#  PROJECT_SOURCE_MAIN: root directory for sources files
################################################################################
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_MAIN
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/*.cpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_CAMERA_SHAPE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/camerashapes/*.cpp")

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_COLOR_HANDLER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/colorhandlers/*.cpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_IO
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/io/*.cpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_IO_IMAGE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/io/image/*.cpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_IO_MESH
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/io/mesh/*.cpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_IO_EXTERNAL
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/io/external/*.cpp")

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_IO_SCENERYV2
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/io/sceneryV2/*.cpp") 
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_LIGHT_SOURCE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/lightsources/*.cpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_MATERIAL
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/materials/*.cpp")

# DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  # PROJECT_SOURCE_MPI
  # "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/mpi/*.cpp")     
      
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_OBJECT_SHAPE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/objectshapes/*.cpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_PHYSIC
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/physics/*.cpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_RAYTRACER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/raytracers/*.cpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_RENDERER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/renderers/*.cpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_STRUCTURE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/structures/*.cpp")     

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_ENVIRONMENT
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/environments/*.cpp")  

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_CORE
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/core/*.cpp")
  
DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_CORE_TASKMANAGER
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/core/taskmanager/*.cpp")

DECLARE_SRC_DIRECTORY (GLOBAL_SOURCE_FILES 
  PROJECT_SOURCE_CORE_TASKEXECUTOR
  "${CMAKE_SOURCE_DIR}/${SOURCE_NAME}/${SOURCE_DIRNAME}/core/taskexecutor/*.cpp")  