#
# Copyright (C) 2012
#

INCLUDE(Version)
IF(UNIX)
  IF(CYGWIN)
    SET(CPACK_GENERATOR "CygwinBinary")
    SET(CPACK_SOURCE_GENERATOR "CygwinBinary")
  ELSE(CYGWIN)
    IF(APPLE)
      SET(CPACK_GENERATOR "PackageMaker")
      SET(CPACK_SOURCE_GENERATOR "PackageMaker")
    ELSE(APPLE)
      SET(CPACK_GENERATOR "${CPACK_GENERATOR};TGZ;DEB")
      # (TGZ;STGZ;DEB;TG;RPM;ZIP; ...)
      SET(CPACK_SOURCE_GENERATOR "${CPACK_SOURCE_GENERATOR};TGZ")
    ENDIF(APPLE)
  ENDIF(CYGWIN)
ELSE(UNIX)
  SET(CPACK_GENERATOR "NSIS")# (TGZ;STGZ;DEB;TG;RPM;ZIP; ...)
  SET(CPACK_SOURCE_GENERATOR "ZIP")
ENDIF(UNIX)

SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY
    "${PROJECT_NAME} - ${${PROJECT_NAME}_PROJECT_SUMMARY}")
SET(CPACK_PACKAGE_CONTACT           "remi.cerise@gmail.fr")
SET(CPACK_PACKAGE_VENDOR            "MAS Laboratory - Ecole Centrale Paris")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Remi Cerise") #required deb
SET(CPACK_PACKAGE_DESCRIPTION_FILE  "${COPYRIGHT_PATH}/readme.txt")
SET(CPACK_RESOURCE_FILE_LICENSE     "${COPYRIGHT_PATH}/copyright.txt")
#version number
SET(CPACK_PACKAGE_VERSION_MAJOR "${${PROJECT_NAME}_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${${PROJECT_NAME}_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH "${${PROJECT_NAME}_PATCH}")
SET(CPACK_PACKAGE_VERSION       "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
SET(CPACK_PACKAGE_ICON ${CMAKE_CURRENT_SOURCE_DIR}/common/logoecp.png)
SET(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
SET(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_PROCESSOR}")

SET(CPACK_PACKAGE_EXECUTABLES "${EXE_TARGET_NAME}" "${EWS_APP_NAME}")

set (CPACK_SOURCE_IGNORE_FILES "~$"   ".svn" ".bz2$" ".gz$"
                               ".tgz" ".zip" ".rpm"  ".stgz"
                               "${CMAKE_CURRENT_BINARY_DIR}/*")

IF(UNIX)
  SET(CPACK_STRIP_FILES "${CMAKE_CURRENT_BINARY_DIR}")
  SET(CPACK_SOURCE_STRIP_FILES "${CMAKE_CURRENT_SOURCE_DIR}")
  SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Remi Cerise") #required deb
  SET(CPACK_DEBIAN_PACKAGE_RECOMMENDS "nvcc,cmake")
ELSE()
# There is a bug in NSI that does not handle full unix paths properly. Make
# sure there is at least one set of four (4) backlasshes.
  SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${PROJECT_NAME}-${EWS_VERSION}")
  SET(CPACK_PACKAGE_ICON "${CMAKE_CURRENT_SOURCE_DIR}/common/logoecp.png")
  SET(CPACK_NSIS_INSTALLED_ICON_NAME "Alinea") #must be change
  SET(CPACK_NSIS_DISPLAY_NAME
      "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
  SET(CPACK_NSIS_HELP_LINK "")
  SET(CPACK_NSIS_URL_INFO_ABOUT "")
  SET(CPACK_NSIS_CONTACT "remi.cerise@gmail.fr")
  SET(CPACK_NSIS_MODIFY_PATH ON)
ENDIF()

INCLUDE(CPack)

