#
# Copyright (C) 2012
#

SET(${PROJECT_NAME}_MAJOR 4) # The major version.
SET(${PROJECT_NAME}_MINOR 5) # The minor version.
SET(${PROJECT_NAME}_PATCH 0)
SET(${PROJECT_NAME}_VERSION ${${PROJECT_NAME}_MAJOR}.${${PROJECT_NAME}_MINOR}.${${PROJECT_NAME}_PATCH})

SET(${PROJECT_NAME}_RELEASE_VERSION "${${PROJECT_NAME}_MAJOR}.${${PROJECT_NAME}_MINOR}")

SET(${PROJECT_NAME}_REVISION_VERSION "")


IF (${PROJECT_NAME}_REVISION_VERSION)
  SET(${PROJECT_NAME}_VERSION ${${PROJECT_NAME}_VERSION}.${${PROJECT_NAME}_REVISION_VERSION})
endIF (${PROJECT_NAME}_REVISION_VERSION)
add_definitions(-D${PROJECT_NAME}_VERSION=${${PROJECT_NAME}_VERSION})


SET(${PROJECT_NAME}_RELEASE "2012-08-01")

INCLUDE(Date)
TODAY(${PROJECT_NAME}_BUILD_VERSION)

